"""ResearchersHub mega skill pack — expands catalog past 750 research skills.

Readable · editable · extensible. Loaded by science_skills alongside core + ext packs.
"""

from __future__ import annotations

from typing import Any, Dict, List


def _s(
    id: str,
    domain: str,
    desc: str,
    *,
    kind: str = "playbook",
    tags: str = "",
    worker: str = "SCRUTATOR",
) -> Dict[str, Any]:
    t = tags.split() if tags else []
    t = list(dict.fromkeys([domain.lower(), "science", "research"] + t))
    return {
        "id": id,
        "worker": worker,
        "desc": desc,
        "kind": kind,
        "tags": t,
        "domain": domain,
        "product": "ResearchersHub",
        "editable": True,
        "extensible": True,
    }


def _pack(domain: str, items: List[tuple], tags: str = "") -> List[Dict[str, Any]]:
    return [_s(i, domain, d, tags=tags) for i, d in items]


def _ml_deep() -> List[Dict[str, Any]]:
    items = [
        ("ml_transformer_train", "Transformer pretrain/finetune checklist"),
        ("ml_attention_viz", "Attention map visualization workflow"),
        ("ml_rope_posenc", "RoPE / positional encoding notes"),
        ("ml_flash_attn", "FlashAttention integration notes"),
        ("ml_kv_cache", "KV-cache inference optimization"),
        ("ml_speculative_decode", "Speculative decoding outline"),
        ("ml_mixture_experts", "MoE routing and load balance"),
        ("ml_rlhf_pipeline", "RLHF preference data + reward model"),
        ("ml_dpo_train", "DPO / preference optimization"),
        ("ml_orpo_train", "ORPO training outline"),
        ("ml_sft_recipe", "Supervised fine-tune data recipe"),
        ("ml_eval_harness", "LLM eval harness (tasks + metrics)"),
        ("ml_benchmark_suite", "Standard NLP/CV benchmark runner plan"),
        ("ml_mt_bench", "Multi-turn chat evaluation"),
        ("ml_toxicity_eval", "Safety/toxicity evaluation suite"),
        ("ml_hallucination_check", "Hallucination detection checklist"),
        ("ml_rag_eval", "RAG faithfulness / context precision"),
        ("ml_chunking_strat", "Document chunking strategies"),
        ("ml_hybrid_search", "Hybrid BM25 + dense retrieval"),
        ("ml_rerank", "Cross-encoder re-ranking"),
        ("ml_agent_tool_use", "Tool-use agent eval harness"),
        ("ml_function_call", "Function-calling schema design"),
        ("ml_structured_out", "JSON/schema-constrained generation"),
        ("ml_guardrails", "Output guardrails policy"),
        ("ml_prompt_version", "Prompt versioning & registry"),
        ("ml_ab_prompts", "A/B prompt experiments"),
        ("ml_cost_latency", "Cost vs latency tradeoff dashboard"),
        ("ml_batch_api", "Batch inference API design"),
        ("ml_streaming_tokens", "Streaming token UX checklist"),
        ("ml_multimodal_vlm", "Vision-language model fine-tune"),
        ("ml_clip_embed", "CLIP-style image-text embeddings"),
        ("ml_diffusion_train", "Diffusion model training outline"),
        ("ml_controlnet", "ControlNet conditioning workflow"),
        ("ml_audio_asr", "ASR fine-tune + WER eval"),
        ("ml_tts_eval", "TTS quality evaluation"),
        ("ml_speech_emotion", "Speech emotion recognition"),
        ("ml_time_series_tft", "Temporal fusion transformer outline"),
        ("ml_prophet_baseline", "Prophet/forecast baseline"),
        ("ml_nbeats", "N-BEATS forecasting outline"),
        ("ml_graph_gnn_train", "Graph neural net train loop"),
        ("ml_graph_sage", "GraphSAGE inductive learning"),
        ("ml_link_predict", "Link prediction eval"),
        ("ml_recsys_cf", "Collaborative filtering baseline"),
        ("ml_recsys_two_tower", "Two-tower retrieval model"),
        ("ml_bandit", "Contextual bandit experiment"),
        ("ml_causal_forest", "Causal forest / uplift modeling"),
        ("ml_doubly_robust", "Doubly robust ATE estimator"),
        ("ml_synth_control", "Synthetic control method"),
        ("ml_iv_estimate", "Instrumental variables outline"),
        ("ml_survival_cox", "Cox PH model + PH assumption checks"),
        ("ml_competing_risks", "Competing risks analysis"),
        ("ml_impute_mice", "MICE multiple imputation"),
        ("ml_missingness", "MCAR/MAR/MNAR diagnostics"),
        ("ml_outlier_iforest", "Isolation forest anomaly detect"),
        ("ml_one_class_svm", "One-class SVM novelty detect"),
        ("ml_auto_ml", "AutoML search budget plan"),
        ("ml_nas_outline", "Neural architecture search outline"),
        ("ml_knowledge_graph", "KG construction + embedding"),
        ("ml_entity_link", "Entity linking pipeline"),
        ("ml_coref", "Coreference resolution notes"),
        ("ml_summarize_eval", "Summarization ROUGE/BERTScore"),
        ("ml_mt_bleu", "Machine translation BLEU/COMET"),
        ("ml_code_gen_eval", "Code generation pass@k eval"),
        ("ml_unit_test_gen", "Unit-test generation workflow"),
        ("ml_static_analysis", "Static analysis in ML CI"),
        ("ml_data_contract", "Data contract / schema validation"),
        ("ml_feature_store", "Feature store design notes"),
        ("ml_online_features", "Online feature serving"),
        ("ml_shadow_deploy", "Shadow deployment checklist"),
        ("ml_canary_model", "Canary model release"),
        ("ml_rollback_plan", "Model rollback runbook"),
        ("ml_model_registry", "Model registry lifecycle"),
        ("ml_lineage_track", "Data/model lineage tracking"),
        ("ml_pii_redact", "PII detection & redaction"),
        ("ml_synth_privacy", "Synthetic data privacy checks"),
        ("ml_watermark", "Model/output watermarking notes"),
        ("ml_adversarial", "Adversarial robustness tests"),
        ("ml_ood_detect", "Out-of-distribution detection"),
        ("ml_domain_adapt", "Domain adaptation strategies"),
        ("ml_continual", "Continual learning checklist"),
        ("ml_few_shot", "Few-shot learning protocols"),
        ("ml_meta_learn", "Meta-learning outline"),
        ("ml_self_super", "Self-supervised pretraining"),
        ("ml_ssl_simclr", "SimCLR-style contrastive SSL"),
        ("ml_mae_pretrain", "Masked autoencoder pretrain"),
        ("ml_distill_teacher", "Teacher-student distillation"),
        ("ml_ensemble", "Model ensembling strategies"),
        ("ml_stacking", "Stacked generalization"),
        ("ml_calibration_temp", "Temperature scaling calibration"),
        ("ml_uncertainty", "Uncertainty quantification"),
        ("ml_bayes_nn", "Bayesian NN approximate inference"),
        ("ml_gaussian_process", "Gaussian process regression"),
        ("ml_bo_loop", "Bayesian optimization experiment loop"),
        ("ml_hpo_optuna", "Optuna HPO workflow"),
        ("ml_ray_tune", "Ray Tune distributed HPO"),
        ("ml_spark_ml", "Spark MLlib pipeline outline"),
        ("ml_polars_etl", "Polars ETL for ML tables"),
        ("ml_duckdb_feature", "DuckDB feature engineering"),
        ("ml_parquet_layout", "Parquet partitioning for training"),
        ("ml_tfrecord", "TFRecord / webdataset packaging"),
        ("ml_dataloader", "Efficient DataLoader tuning"),
        ("ml_mixed_precision", "AMP mixed-precision training"),
        ("ml_grad_accum", "Gradient accumulation recipes"),
        ("ml_grad_checkpoint", "Activation checkpointing"),
        ("ml_fsdp", "FSDP / ZeRO sharding notes"),
        ("ml_deepspeed", "DeepSpeed config checklist"),
        ("ml_tensorrt", "TensorRT export & optimize"),
        ("ml_onnx_runtime", "ONNX Runtime deploy"),
        ("ml_openvino", "OpenVINO optimization"),
        ("ml_coreml", "Core ML conversion notes"),
        ("ml_tflite", "TFLite mobile deploy"),
        ("ml_edge_quant", "Edge quantization checklist"),
        ("ml_observability", "ML observability stack plan"),
        ("ml_drift_psi", "PSI/KS drift monitoring"),
        ("ml_label_studio", "Labeling tool workflow"),
        ("ml_active_batch", "Batch active learning"),
        ("ml_weak_snorkel", "Weak supervision labeling functions"),
        ("ml_data_cent_ai", "Data-centric AI iteration loop"),
        ("ml_slice_discovery", "Error slice discovery"),
        ("ml_subgroup_fair", "Subgroup fairness metrics"),
        ("ml_counterfactual", "Counterfactual explanation"),
        ("ml_concept_act", "Concept activation vectors"),
        ("ml_mech_interp", "Mechanistic interpretability notes"),
        ("ml_sae_features", "Sparse autoencoder feature discovery"),
        ("ml_repro_lockfile", "Lockfile + seed full repro"),
        ("ml_paper_repro", "Paper reproduction checklist"),
    ]
    return _pack("ml", items, "ml deep-learning")


def _compbio_deep() -> List[Dict[str, Any]]:
    items = [
        ("cbi_long_read", "Long-read sequencing analysis"),
        ("cbi_ont_basecall", "ONT basecalling QC"),
        ("cbi_pacbio_ccs", "PacBio HiFi analysis outline"),
        ("cbi_structural_var", "Structural variant calling"),
        ("cbi_cnv_call", "CNV detection workflow"),
        ("cbi_fusion_gene", "Gene fusion detection"),
        ("cbi_hla_type", "HLA typing from NGS"),
        ("cbi_tcr_bcr", "TCR/BCR repertoire analysis"),
        ("cbi_neoantigen", "Neoantigen prediction pipeline"),
        ("cbi_immunopeptidomics", "Immunopeptidomics outline"),
        ("cbi_scrna_doublet", "Doublet detection scRNA"),
        ("cbi_scrna_harmony", "Harmony batch integration"),
        ("cbi_scrna_scvi", "scVI integration outline"),
        ("cbi_multiome", "Multiome RNA+ATAC joint analysis"),
        ("cbi_cite_seq", "CITE-seq protein+RNA"),
        ("cbi_spatial_deconv", "Spatial deconvolution"),
        ("cbi_visium", "Visium spatial pipeline"),
        ("cbi_xenium", "Xenium spatial notes"),
        ("cbi_cell_comm", "Cell-cell communication (ligand-receptor)"),
        ("cbi_grn_scenic", "SCENIC GRN inference"),
        ("cbi_perturb_seq", "Perturb-seq analysis"),
        ("cbi_crispri_screen", "CRISPRi/a screen analysis"),
        ("cbi_base_edit", "Base/prime editing design"),
        ("cbi_offtarget", "CRISPR off-target assessment"),
        ("cbi_prime_edit", "Prime editing guide design"),
        ("cbi_aav_design", "AAV vector design notes"),
        ("cbi_lnp_rna", "LNP mRNA formulation checklist"),
        ("cbi_codon_opt", "Codon optimization"),
        ("cbi_promoter_design", "Promoter/enhancer design"),
        ("cbi_synthetic_circuit", "Genetic circuit design"),
        ("cbi_metabolic_fba", "Flux balance analysis"),
        ("cbi_genome_scale_model", "GEM model curation"),
        ("cbi_phage", "Phage genomics outline"),
        ("cbi_amr_gene", "AMR gene detection"),
        ("cbi_mlst", "MLST typing"),
        ("cbi_pangenome", "Pangenome analysis"),
        ("cbi_comparative_genomics", "Comparative genomics"),
        ("cbi_ortholog", "Ortholog inference"),
        ("cbi_synteny", "Synteny mapping"),
        ("cbi_popgen", "Population genetics stats"),
        ("cbi_selection_scan", "Selection scan methods"),
        ("cbi_admixture", "Admixture analysis"),
        ("cbi_ibd", "IBD segment detection"),
        ("cbi_imputation_genotype", "Genotype imputation"),
        ("cbi_gwas_gcta", "GCTA / heritability"),
        ("cbi_ldsc", "LD score regression"),
        ("cbi_colocalization", "eQTL-GWAS colocalization"),
        ("cbi_twmr", "TWAS / MR outline"),
        ("cbi_phewas", "PheWAS design"),
        ("cbi_ehr_phenotype", "EHR phenotyping"),
        ("cbi_clinical_nlp", "Clinical NLP extraction"),
        ("cbi_imaging_omics", "Radiomics + omics fusion"),
        ("cbi_pathology_ai", "Digital pathology ML outline"),
        ("cbi_drug_repurpose", "Drug repurposing pipeline"),
        ("cbi_connectivity_map", "Connectivity map analysis"),
        ("cbi_network_medicine", "Network medicine modules"),
        ("cbi_patient_similarity", "Patient similarity networks"),
        ("cbi_digital_twin", "Digital twin patient model notes"),
        ("cbi_trial_emulation", "Target trial emulation"),
        ("cbi_rwe", "Real-world evidence checklist"),
        ("cbi_biomarker_validate", "Biomarker validation stages"),
        ("cbi_assay_cv", "Assay coefficient of variation QC"),
        ("cbi_plate_effect", "Plate effect normalization"),
        ("cbi_spike_in", "Spike-in controls design"),
        ("cbi_ercc", "ERCC spike-in analysis"),
        ("cbi_umi_correct", "UMI error correction"),
        ("cbi_barcode_qc", "Cell barcode QC"),
        ("cbi_ambient_rna", "Ambient RNA correction"),
        ("cbi_soupx", "SoupX ambient correction"),
        ("cbi_cellbender", "CellBender outline"),
        ("cbi_velocity", "RNA velocity analysis"),
        ("cbi_paga", "PAGA graph abstraction"),
        ("cbi_cyclone", "Cell cycle scoring"),
        ("cbi_module_score", "Gene module scoring"),
        ("cbi_gsea_prerank", "Preranked GSEA"),
        ("cbi_gsva", "GSVA pathway scores"),
        ("cbi_progeny", "PROGENy pathway activity"),
        ("cbi_dorothea", "DoRothEA TF activity"),
        ("cbi_motif_enrich", "Motif enrichment (HOMER-style)"),
        ("cbi_footprint", "TF footprinting"),
        ("cbi_peak_anno", "Peak annotation"),
        ("cbi_diffbind", "Differential binding"),
        ("cbi_hic_tads", "TAD calling Hi-C"),
        ("cbi_loop_call", "Chromatin loop calling"),
        ("cbi_abc_model", "ABC enhancer-gene model"),
        ("cbi_eqtl_map", "cis-eQTL mapping"),
        ("cbi_sqtl", "sQTL splicing QTL"),
        ("cbi_pqtl", "pQTL proteomics QTL"),
        ("cbi_mQTL", "mQTL methylation QTL"),
        ("cbi_multi_qtl", "Multi-omics QTL integration"),
        ("cbi_fair_genomics", "FAIR genomics packaging"),
        ("cbi_ga4gh", "GA4GH standards checklist"),
        ("cbi_vcf_validate", "VCF validation & stats"),
        ("cbi_bco", "BioCompute Object packaging"),
        ("cbi_workflow_cwl", "CWL/Nextflow workflow design"),
        ("cbi_containers_bioc", "Biocontainers reproducibility"),
    ]
    return _pack("compbio", items, "compbio genomics")


def _cheminf_deep() -> List[Dict[str, Any]]:
    items = [
        ("cheminf_rdkit_sanitize", "RDKit sanitize & cleanup"),
        ("cheminf_salt_strip", "Salt/solvent stripping"),
        ("cheminf_neutralize", "Charge neutralization"),
        ("cheminf_standardize", "MolStandardize pipeline"),
        ("cheminf_duplicate_remove", "Duplicate structure removal"),
        ("cheminf_stereo_enum", "Stereo enumeration"),
        ("cheminf_confab", "Confab conformer generation"),
        ("cheminf_etkdg", "ETKDG conformer workflow"),
        ("cheminf_mmff_min", "MMFF minimization"),
        ("cheminf_uff_min", "UFF minimization"),
        ("cheminf_pharmacophore_3d", "3D pharmacophore"),
        ("cheminf_rocs_shape", "ROCS-style shape screening"),
        ("cheminf_esp_map", "Electrostatic potential map"),
        ("cheminf_dock_vina", "AutoDock Vina workflow"),
        ("cheminf_dock_glide", "Glide-style docking notes"),
        ("cheminf_pose_cluster", "Pose clustering"),
        ("cheminf_plip", "Protein-ligand interaction profile"),
        ("cheminf_water_sites", "Water site analysis"),
        ("cheminf_fep_setup", "FEP setup checklist"),
        ("cheminf_ti_md", "Thermodynamic integration MD"),
        ("cheminf_rbfe", "Relative binding free energy"),
        ("cheminf_abfe", "Absolute binding free energy"),
        ("cheminf_qsar_rf", "Random forest QSAR"),
        ("cheminf_qsar_gp", "GP QSAR + uncertainty"),
        ("cheminf_qsar_gnn", "Graph neural QSAR"),
        ("cheminf_activity_cliff", "Activity cliff detection"),
        ("cheminf_sar_matrix", "SAR matrix analysis"),
        ("cheminf_mmpdb", "Matched molecular pair DB"),
        ("cheminf_rgroup_decomp", "R-group table generation"),
        ("cheminf_frag_link", "Fragment linking design"),
        ("cheminf_frag_grow", "Fragment growing"),
        ("cheminf_fbdd", "FBDD cascade"),
        ("cheminf_htl", "Hit-to-lead checklist"),
        ("cheminf_lead_opt", "Lead optimization multi-param"),
        ("cheminf_cns_mpo", "CNS MPO scoring"),
        ("cheminf_ppp", "Property forecast plots"),
        ("cheminf_solubility", "Aqueous solubility models"),
        ("cheminf_permeability", "Permeability prediction"),
        ("cheminf_clearance", "Metabolic clearance models"),
        ("cheminf_herg", "hERG liability filter"),
        ("cheminf_cyp", "CYP inhibition alerts"),
        ("cheminf_ames", "Ames mutagenicity notes"),
        ("cheminf_reactive", "Reactive metabolite flags"),
        ("cheminf_prodrug", "Prodrug design notes"),
        ("cheminf_protac", "PROTAC design outline"),
        ("cheminf_macrocycle", "Macrocycle design notes"),
        ("cheminf_peptide", "Peptide drug-likeness"),
        ("cheminf_oligo", "Oligonucleotide chem notes"),
        ("cheminf_adc", "Antibody-drug conjugate linker notes"),
        ("cheminf_crystal_struct", "Small-molecule crystallography"),
        ("cheminf_powder_xrd", "Powder XRD phase ID"),
        ("cheminf_polymorph_screen", "Polymorph screening plan"),
        ("cheminf_salt_screen", "Salt/cocrystal screen"),
        ("cheminf_formulation", "Formulation preformulation"),
        ("cheminf_stability_ich", "ICH stability study design"),
        ("cheminf_impurity", "Impurity profiling"),
        ("cheminf_genotoxic", "Genotoxic impurity control"),
        ("cheminf_process_chem", "Process chemistry route scouting"),
        ("cheminf_route_score", "Route ideality / PMI scoring"),
        ("cheminf_catalyst_screen", "Catalyst screening DoE"),
        ("cheminf_flow_chem", "Flow chemistry parameters"),
        ("cheminf_photoredox", "Photoredox reaction design"),
        ("cheminf_electrochem_syn", "Electrosynthesis notes"),
        ("cheminf_biocatalysis", "Biocatalysis route design"),
        ("cheminf_enzyme_eng", "Enzyme engineering for chem"),
        ("cheminf_retrosyn_ai", "AI retrosynthesis planning"),
        ("cheminf_synth_plan", "Multi-step synthesis planning"),
        ("cheminf_inventory_eln", "Chemical inventory + ELN link"),
        ("cheminf_sds_parse", "SDS hazard extraction"),
        ("cheminf_ghs_label", "GHS labeling checklist"),
        ("cheminf_green_solvent", "Green solvent selection"),
        ("cheminf_lca_chem", "LCA for chemical process"),
        ("cheminf_patent_fto", "Freedom-to-operate sketch"),
        ("cheminf_scaffold_ip", "Scaffold IP landscaping"),
        ("cheminf_pubchem_mine", "PubChem data mining"),
        ("cheminf_zinc_screen", "ZINC library screening plan"),
        ("cheminf_enamine", "Enamine REAL space notes"),
        ("cheminf_chembl_sar", "ChEMBL SAR extraction"),
        ("cheminf_pdbbind", "PDBbind affinity dataset"),
        ("cheminf_dude", "DUD-E virtual screen benchmark"),
        ("cheminf_litpcba", "LIT-PCBA benchmark notes"),
        ("cheminf_moleculenet", "MoleculeNet benchmark suite"),
        ("cheminf_therapeutics_data", "Therapeutic data packaging"),
        ("cheminf_fair_mol", "FAIR molecular datasets"),
        ("cheminf_smiles_aug", "SMILES augmentation for ML"),
        ("cheminf_selfies", "SELFIES representation"),
        ("cheminf_graphormer", "Molecular Graphormer outline"),
        ("cheminf_3d_inf", "3D-informed molecular ML"),
        ("cheminf_dock_ml_score", "ML docking score models"),
        ("cheminf_active_learn_vs", "Active learning virtual screen"),
        ("cheminf_multiobj_pareto", "Pareto multi-obj mol design"),
        ("cheminf_bayes_opt_mol", "Bayesian optimization molecules"),
        ("cheminf_rl_mol", "RL molecule generation"),
        ("cheminf_vae_mol", "Molecular VAE generation"),
        ("cheminf_gan_mol", "Molecular GAN outline"),
        ("cheminf_diff_mol", "Diffusion molecular generation"),
        ("cheminf_cond_gen", "Property-conditioned generation"),
        ("cheminf_scaffold_cond", "Scaffold-conditioned gen"),
        ("cheminf_reaction_pred", "Reaction outcome prediction"),
        ("cheminf_yield_model", "Reaction yield models"),
        ("cheminf_condition_rec", "Condition recommendation"),
        ("cheminf_retrosyn_eval", "Retrosynthesis eval metrics"),
    ]
    return _pack("cheminformatics", items, "cheminformatics qsar")


def _clinical_stats() -> List[Dict[str, Any]]:
    items = [
        ("clin_protocol_synopsis", "Clinical protocol synopsis template"),
        ("clin_sap", "Statistical analysis plan skeleton"),
        ("clin_randomization", "Randomization schedule design"),
        ("clin_stratify", "Stratified randomization"),
        ("clin_block_rand", "Block randomization"),
        ("clin_blinding", "Blinding integrity checklist"),
        ("clin_sample_size_survival", "Survival sample size"),
        ("clin_sample_size_binary", "Binary endpoint sample size"),
        ("clin_interim", "Interim analysis / alpha spend"),
        ("clin_dmc", "DMC charter notes"),
        ("clin_endpoint_def", "Endpoint definition"),
        ("clin_estimand", "ICH E9(R1) estimand framework"),
        ("clin_itt_pp", "ITT vs per-protocol analysis"),
        ("clin_missing_data", "Missing data strategies"),
        ("clin_mmrm", "MMRM longitudinal analysis"),
        ("clin_mixed_model", "Mixed-effects models"),
        ("clin_gee", "GEE correlated outcomes"),
        ("clin_time_to_event", "Time-to-event analysis suite"),
        ("clin_landmark", "Landmark analysis"),
        ("clin_rmst", "Restricted mean survival time"),
        ("clin_competing", "Competing risks clinical"),
        ("clin_subgroup", "Pre-specified subgroup analysis"),
        ("clin_interaction", "Treatment-by-covariate interaction"),
        ("clin_multiplicity", "Multiplicity adjustment"),
        ("clin_bayes_trial", "Bayesian adaptive trial outline"),
        ("clin_platform_trial", "Platform trial design"),
        ("clin_basket", "Basket trial design"),
        ("clin_umbrella", "Umbrella trial design"),
        ("clin_n_of_1", "N-of-1 trial design"),
        ("clin_crossover", "Crossover design analysis"),
        ("clin_cluster_rct", "Cluster RCT design"),
        ("clin_stepped_wedge", "Stepped-wedge design"),
        ("clin_noninferior", "Non-inferiority margin"),
        ("clin_equivalence", "Equivalence trial design"),
        ("clin_pk_nca", "PK noncompartmental analysis"),
        ("clin_pkpd", "PK/PD modeling outline"),
        ("clin_pop_pk", "Population PK notes"),
        ("clin_bioequivalence", "Bioequivalence stats"),
        ("clin_safety_ae", "AE coding & signal detection"),
        ("clin_lab_shift", "Lab shift tables"),
        ("clin_qt", "QT/QTc analysis notes"),
        ("clin_immunogenicity", "Immunogenicity analysis"),
        ("clin_ada", "Anti-drug antibody assessment"),
        ("clin_biomarker_strat", "Biomarker-stratified design"),
        ("clin_cdisc_sdtm", "CDISC SDTM mapping notes"),
        ("clin_adam", "ADaM analysis datasets"),
        ("clin_define_xml", "Define-XML checklist"),
        ("clin_tlf", "TLF shell generation plan"),
        ("clin_csr", "CSR structure checklist"),
        ("clin_reg_submit", "Regulatory submission package"),
        ("clin_fda_guidance", "FDA guidance mapping"),
        ("clin_ema_guidance", "EMA guidance mapping"),
        ("clin_ich_gcp", "ICH GCP compliance checklist"),
        ("clin_informed_consent", "Informed consent elements"),
        ("clin_dsmb", "DSMB report template"),
        ("clin_pharmacovigilance", "Pharmacovigilance signal triage"),
        ("clin_rwe_study", "RWE study protocol"),
        ("clin_claims_data", "Claims data analysis caveats"),
        ("clin_ehr_extract", "EHR extract QC"),
        ("clin_propensity", "Propensity score methods"),
        ("clin_iptw", "IPTW weighting diagnostics"),
        ("clin_matching", "PS matching balance tables"),
        ("clin_sensitivity", "Sensitivity analysis suite"),
        ("clin_evalue", "E-value for confounding"),
        ("clin_meta_rct", "RCT meta-analysis"),
        ("clin_network_meta", "Network meta-analysis"),
        ("clin_ipd_meta", "IPD meta-analysis"),
        ("clin_forest_clin", "Clinical forest plot chart"),
        ("clin_km_plot", "Kaplan–Meier publication figure"),
        ("clin_waterfall", "Waterfall tumor response plot"),
        ("clin_swimmer", "Swimmer plot"),
        ("clin_spider", "Spider plot tumor change"),
        ("clin_consort_flow", "CONSORT flow diagram data"),
    ]
    return _pack("clinical", items, "clinical stats trials")


def _materials_physics() -> List[Dict[str, Any]]:
    items = [
        ("mat_dft_geo_opt", "DFT geometry optimization"),
        ("mat_dft_band", "Band structure calculation plan"),
        ("mat_dft_dos", "Density of states workflow"),
        ("mat_phonon", "Phonon / thermal properties"),
        ("mat_neb", "NEB transition state search"),
        ("mat_surface_slab", "Surface slab model setup"),
        ("mat_adsorption", "Adsorption energy workflow"),
        ("mat_catalyst_screen", "Catalyst descriptor screening"),
        ("mat_phase_predict", "Phase stability prediction"),
        ("mat_convex_hull", "Convex hull construction"),
        ("mat_elastic_tensor", "Elastic tensor calculation"),
        ("mat_thermal_cond", "Thermal conductivity models"),
        ("mat_battery_electrode", "Battery electrode materials screen"),
        ("mat_seebeck", "Thermoelectric Seebeck estimate"),
        ("mat_perovskite", "Perovskite stability heuristics"),
        ("mat_mof_design", "MOF design notes"),
        ("mat_polymer_md", "Polymer MD setup"),
        ("mat_glass_transition", "Glass transition estimation"),
        ("mat_fatigue", "Fatigue life analysis"),
        ("mat_fracture", "Fracture toughness notes"),
        ("mat_corrosion_eis", "EIS corrosion analysis"),
        ("mat_sem_eds", "SEM/EDS interpretation"),
        ("mat_tem", "TEM image analysis notes"),
        ("mat_afm", "AFM data processing"),
        ("mat_xps", "XPS peak fitting"),
        ("mat_xrd_refine", "Rietveld refinement outline"),
        ("mat_saxs", "SAXS analysis"),
        ("mat_rheology", "Rheology curve interpretation"),
        ("mat_dsc", "DSC thermal analysis"),
        ("mat_tga", "TGA decomposition analysis"),
        ("mat_dma", "DMA viscoelastic analysis"),
        ("phys_qm_perturb", "Quantum perturbation theory notes"),
        ("phys_scattering", "Scattering cross-section basics"),
        ("phys_laser_matter", "Laser-matter interaction notes"),
        ("phys_plasma", "Plasma parameter estimates"),
        ("phys_fluid_cfd", "CFD setup checklist"),
        ("phys_turbulence", "Turbulence model selection"),
        ("phys_heat_transfer", "Heat transfer calculation"),
        ("phys_em_wave", "EM wave propagation notes"),
        ("phys_antenna", "Antenna parameter basics"),
        ("phys_optics_fourier", "Fourier optics simulation"),
        ("phys_interferometry", "Interferometry analysis"),
        ("phys_cryogenics", "Cryogenics system notes"),
        ("phys_superconductor", "Superconductor Tc heuristics"),
        ("phys_spintronics", "Spintronics device notes"),
        ("phys_quantum_sensor", "Quantum sensor metrics"),
        ("phys_metrology", "Metrology uncertainty budget"),
        ("phys_units_si", "SI unit consistency checker"),
        ("phys_dimensional", "Dimensional analysis"),
        ("phys_error_prop", "Uncertainty propagation"),
    ]
    return _pack("materials", items, "materials physics dft")


def _earth_climate() -> List[Dict[str, Any]]:
    items = [
        ("earth_gis_crs", "CRS / projection handling"),
        ("earth_raster_zonal", "Zonal statistics on rasters"),
        ("earth_vector_overlay", "Vector overlay analysis"),
        ("earth_remote_ndvi", "NDVI time series"),
        ("earth_landsat", "Landsat preprocessing"),
        ("earth_sentinel", "Sentinel-2 workflow"),
        ("earth_sar", "SAR backscatter analysis"),
        ("earth_dem", "DEM derivatives (slope/aspect)"),
        ("earth_hydrology", "Watershed delineation"),
        ("earth_climate_normals", "Climate normals calculation"),
        ("earth_extreme_events", "Extreme value analysis weather"),
        ("earth_downscale", "Climate downscaling outline"),
        ("earth_carbon_budget", "Carbon budget accounting"),
        ("earth_lulc", "Land use/land cover classify"),
        ("earth_species_dist", "Species distribution modeling"),
        ("earth_air_quality", "Air quality index analysis"),
        ("earth_ocean_sst", "SST anomaly analysis"),
        ("earth_seismic", "Seismic catalog analysis"),
        ("earth_soil", "Soil property mapping"),
        ("earth_repro_geo", "Reproducible geospatial pipeline"),
    ]
    return _pack("earth", items, "earth climate gis")


def _neuro_cog() -> List[Dict[str, Any]]:
    items = [
        ("neuro_eeg_preprocess", "EEG preprocess pipeline"),
        ("neuro_erp", "ERP analysis"),
        ("neuro_meg", "MEG analysis outline"),
        ("neuro_fmri_pre", "fMRI preprocessing"),
        ("neuro_glm_fmri", "fMRI GLM first-level"),
        ("neuro_connectivity", "Functional connectivity"),
        ("neuro_dti", "DTI tractography notes"),
        ("neuro_freesurfer", "FreeSurfer recon notes"),
        ("neuro_bids", "BIDS dataset validation"),
        ("neuro_eye_track", "Eye-tracking analysis"),
        ("neuro_behavior", "Behavioral task analysis"),
        ("neuro_psychometrics", "Psychometric scale analysis"),
        ("neuro_sleep", "Sleep stage scoring notes"),
        ("neuro_bci", "BCI feature + classify outline"),
        ("neuro_spike", "Spike sorting basics"),
        ("neuro_calcium", "Calcium imaging analysis"),
        ("neuro_network_graph", "Brain network graph metrics"),
        ("neuro_lesion", "Lesion-symptom mapping"),
        ("neuro_repro_neuro", "Neuroimaging repro checklist"),
        ("neuro_prereg_cog", "Cognitive study pre-reg"),
    ]
    return _pack("neuroscience", items, "neuroscience cognition")


def _astro_space() -> List[Dict[str, Any]]:
    items = [
        ("astro_photometry", "Aperture photometry workflow"),
        ("astro_astrometry", "Astrometric calibration"),
        ("astro_spectra", "Stellar spectrum reduction"),
        ("astro_lightcurve", "Exoplanet light curve fit"),
        ("astro_periodogram", "Periodogram analysis"),
        ("astro_catalog_cross", "Catalog cross-match"),
        ("astro_fits_io", "FITS I/O + WCS"),
        ("astro_image_stack", "Image stacking / drizzle"),
        ("astro_psf", "PSF modeling"),
        ("astro_cosmo_distance", "Cosmological distance calc"),
        ("space_orbit", "Orbital element conversion"),
        ("space_tle", "TLE propagation notes"),
        ("space_link_budget", "RF link budget"),
        ("space_thermal", "Spacecraft thermal budget"),
        ("space_rad_hard", "Radiation hardness notes"),
    ]
    return _pack("astro", items, "astronomy space")


def _robotics_eng() -> List[Dict[str, Any]]:
    items = [
        ("robo_kinematics", "Forward/inverse kinematics"),
        ("robo_trajectory", "Trajectory planning"),
        ("robo_pid_tune", "PID tuning workflow"),
        ("robo_slam", "SLAM pipeline outline"),
        ("robo_perception", "Robot vision perception stack"),
        ("robo_calibration", "Camera/IMU calibration"),
        ("robo_ros2", "ROS 2 package layout"),
        ("robo_sim_gazebo", "Gazebo/sim testing plan"),
        ("robo_safety", "Robot safety checklist"),
        ("robo_hri", "Human-robot interaction study"),
        ("eng_doe_taguchi", "Taguchi DoE"),
        ("eng_six_sigma", "Six Sigma DMAIC template"),
        ("eng_fmea", "FMEA risk analysis"),
        ("eng_tolerance", "Tolerance stack-up"),
        ("eng_fea", "FEA setup checklist"),
        ("eng_cad_bom", "CAD BOM hygiene"),
        ("eng_reliability", "Reliability bathtub curve"),
        ("eng_mtbf", "MTBF estimation"),
        ("eng_power_budget", "Electronics power budget"),
        ("eng_signal_integrity", "Signal integrity notes"),
    ]
    return _pack("engineering", items, "robotics engineering")


def _data_platform() -> List[Dict[str, Any]]:
    items = [
        ("data_lakehouse", "Lakehouse table design"),
        ("data_medallion", "Medallion architecture"),
        ("data_dbt_model", "dbt model testing"),
        ("data_great_expectations", "Great Expectations suite"),
        ("data_soda_scan", "Data quality scan"),
        ("data_lineage_openlineage", "OpenLineage events"),
        ("data_catalog", "Data catalog metadata"),
        ("data_privacy_gdpr", "GDPR data handling checklist"),
        ("data_hipaa", "HIPAA research data notes"),
        ("data_anonymize", "Anonymization / k-anonymity"),
        ("data_synthetic_tab", "Tabular synthetic data"),
        ("data_stream_kafka", "Kafka stream processing plan"),
        ("data_spark_job", "Spark job tuning"),
        ("data_airflow_dag", "Airflow DAG design"),
        ("data_prefect", "Prefect flow design"),
        ("data_version_lake", "Lake dataset versioning"),
        ("data_sql_optimize", "SQL query optimization"),
        ("data_window_func", "Advanced window functions"),
        ("data_time_travel", "Time-travel query patterns"),
        ("data_cdc", "CDC pipeline design"),
        ("data_api_paginate", "API pagination & rate respect"),
        ("data_scrape_ethics", "Ethical scraping checklist"),
        ("data_ocr_table", "OCR table extraction"),
        ("data_pdf_parse", "Scientific PDF parse"),
        ("data_bib_manage", "Bibliography database hygiene"),
        ("data_orcid", "ORCID researcher graph"),
        ("data_doi_mint", "DOI minting checklist"),
        ("data_zenodo", "Zenodo deposit workflow"),
        ("data_figshare", "Figshare packaging"),
        ("data_dryad", "Dryad deposit notes"),
    ]
    return _pack("data_platform", items, "data platform repro")


def _viz_writing() -> List[Dict[str, Any]]:
    items = [
        ("viz_nature_figure", "Nature-style figure checklist"),
        ("viz_colorblind", "Colorblind-safe palettes"),
        ("viz_small_multiples", "Small multiples layout"),
        ("viz_upset", "UpSet plot for set intersections"),
        ("viz_alluvial", "Alluvial / Sankey diagram"),
        ("viz_ridge", "Ridge density plot"),
        ("viz_volcano", "Volcano plot (omics)"),
        ("viz_manhattan", "Manhattan plot"),
        ("viz_circos", "Circos-style genome plot"),
        ("viz_3d_scatter", "3D scatter interactive notes"),
        ("viz_animation", "Scientific animation ethics"),
        ("viz_dashboard", "Research dashboard IA"),
        ("write_abstract", "Structured abstract"),
        ("write_cover_letter", "Journal cover letter"),
        ("write_response_reviewers", "Response to reviewers"),
        ("write_grant_aims", "Grant specific aims page"),
        ("write_budget_just", "Budget justification"),
        ("write_biosketch", "NIH-style biosketch notes"),
        ("write_data_avail", "Data availability statement"),
        ("write_code_avail", "Code availability statement"),
        ("write_limitations", "Limitations section rigor"),
        ("write_stats_report", "SAMPL reporting stats"),
        ("write_preprint", "Preprint deposit checklist"),
        ("write_press", "Lay summary / press brief"),
        ("write_poster", "Conference poster structure"),
        ("write_talk", "Scientific talk storyboard"),
        ("write_methods_repro", "Methods reproducibility block"),
        ("write_supplement", "Supplement organization"),
        ("write_figure_legend", "Figure legend completeness"),
        ("write_table1", "Table 1 baseline characteristics"),
    ]
    return _pack("comms", items, "visualization writing")


def _atlas_agents() -> List[Dict[str, Any]]:
    items = [
        ("atlas_add_claim", "Add claim node to Atlas graph"),
        ("atlas_add_paper", "Add paper node + cite edges"),
        ("atlas_add_dataset", "Register dataset in Atlas"),
        ("atlas_add_experiment", "Log experiment node"),
        ("atlas_link_figure", "Link figure to experiment"),
        ("atlas_link_script", "Link script to result"),
        ("atlas_export_subgraph", "Export subgraph JSON"),
        ("atlas_query_neighbors", "Query node neighbors"),
        ("atlas_replicate_edge", "Mark replication edge"),
        ("atlas_refute_edge", "Mark refutation edge"),
        ("atlas_agent_handoff", "Agent handoff via graph"),
        ("atlas_merge_claims", "Merge duplicate claims"),
        ("atlas_evidence_score", "Score claim evidence weight"),
        ("atlas_timeline", "Research timeline from events"),
        ("atlas_repro_bundle", "Bundle graph + scripts + figures"),
        ("agent_chemist", "Chemist agent skill routing"),
        ("agent_biologist", "Biologist agent skill routing"),
        ("agent_ml_scientist", "ML scientist agent routing"),
        ("agent_statistician", "Statistician agent routing"),
        ("agent_writer", "Scientific writer agent routing"),
        ("agent_reviewer", "Critical reviewer agent"),
        ("agent_lab_ops", "Lab ops agent routing"),
        ("agent_data_eng", "Data engineer agent routing"),
        ("agent_safety", "Safety/compliance agent"),
        ("agent_orchestrator", "Multi-agent research orchestrator"),
    ]
    return _pack("atlas", items, "atlas agents graph")


def _quantum_theory() -> List[Dict[str, Any]]:
    items = [
        ("quantum_circuit", "Quantum circuit design basics"),
        ("quantum_vqe", "VQE algorithm outline"),
        ("quantum_qaoa", "QAOA outline"),
        ("quantum_error", "Error mitigation notes"),
        ("quantum_sim", "Statevector sim checklist"),
        ("theory_lagrangian", "Lagrangian mechanics notes"),
        ("theory_hamiltonian", "Hamiltonian systems"),
        ("theory_symmetry", "Symmetry / Noether notes"),
        ("theory_stat_mech", "Stat mech ensemble calc"),
        ("theory_info", "Information theory metrics"),
        ("theory_optim", "Convex optimization outline"),
        ("theory_control", "Control theory basics"),
        ("theory_signal", "Signal processing transforms"),
        ("theory_numerics", "Numerical stability checklist"),
        ("theory_mcmc", "MCMC diagnostics"),
    ]
    return _pack("theory", items, "quantum theory math")


def all_mega_skills() -> List[Dict[str, Any]]:
    packs = [
        _ml_deep(),
        _compbio_deep(),
        _cheminf_deep(),
        _clinical_stats(),
        _materials_physics(),
        _earth_climate(),
        _neuro_cog(),
        _astro_space(),
        _robotics_eng(),
        _data_platform(),
        _viz_writing(),
        _atlas_agents(),
        _quantum_theory(),
    ]
    seen = set()
    out: List[Dict[str, Any]] = []
    for pack in packs:
        for s in pack:
            if s["id"] in seen:
                continue
            seen.add(s["id"])
            out.append(s)
    return out


def mega_count() -> int:
    return len(all_mega_skills())
